# Generated by Django 3.0.5 on 2020-07-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_noteboard_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.TextField(verbose_name='токен'),
        ),
    ]
