# Generated by Django 3.0.6 on 2020-07-16 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200710_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteboard',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
