# Generated by Django 2.2.13 on 2020-07-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0005_noteboard_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_link', models.CharField(max_length=40, verbose_name='ссылка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.NoteBoard')),
            ],
        ),
    ]
