# Generated by Django 2.2.13 on 2020-07-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedNotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharednotes',
            old_name='user',
            new_name='note_from_board',
        ),
    ]
